site_name: Morpheus

repo_url: https://github.com/zavtech/morpheus-core

site_author: Xavier Witdouck

copyright: Copyright (C) 2014-2017 Xavier Witdouck

extra_css:
  - ./css/morpheus.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/styles/default.min.css


extra_javascript:
  - https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/highlight.min.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML
  - http://www.zavtech.com/morpheus/docs/javascript/analytics.js


pages:
  - Overview: index.md
  - Array:
    - Overview: array/overview.md
    - Performance: array/performance.md
  - DataFrame:
    - Construction: frame/construction.md
    - Accessing: frame/access.md
    - Reshaping: frame/reshaping.md
    - Filtering: frame/filtering.md
    - Sorting: frame/sorting.md
    - Grouping: frame/grouping.md
    - Finding: frame/finding.md
    - Writing: frame/writing.md
    - Performance: frame/performance.md
  - Analysis:
    - Descriptive Statistics: analysis/statistics.md
    - Linear Regression:
        - Ordinary Least Squares: regression/ols.md
        - Weighted Least Squares: regression/wls.md
        - Generalized Least Squares: regression/gls.md
    - Principal Component Analysis: analysis/pca.md
    - Linear Algebra: analysis/linearalgebra.md
    - Time Series Analysis: analysis/timeseries.md
  - Visualization:
      - Charts: viz/charts.md
      - Tables: viz/tables.md
  - Data Sources:
    - Quandl: providers/quandl.md
    - Google Finance: providers/google.md
    - Yahoo Finance: providers/yahoo.md
    - Federal Reserve: providers/fred.md
    - World Bank: providers/world-bank.md

